"""
WAAM LS Code Generator
======================
Generates Fanuc R-30iB LS programs from WAAM slicer layer data.

Motion logic:
  Within a layer:
    One air move (L at R[1], same Z) to next segment start
    Weld Start / weld points at R[2] / Weld End per segment
    No Z lift between segments (wire retract handles isolation)
    Edge passes written at their explicit mm/sec speed

  Between layers (when lift_clearance_mm > 0):
    Lift straight up (L at R[1])
    Travel across to next layer start XY (L at R[1])
    Descend to next layer Z (L at R[1])
    Layer comment + WAIT R[3]

  Between layers (when lift_clearance_mm = 0):
    Single air move directly to next layer start (L at R[1])
    Layer comment + WAIT R[3]

Point reduction:
  Curves are simplified using Douglas-Peucker algorithm before writing.
  This removes up to 95% of redundant curve points while maintaining
  chord deviation below curve_tolerance_mm.

Coordinates use STL frame directly.
Apply robot world frame offset separately before running on machine.
"""

from dataclasses import dataclass, field
from typing import List, Tuple, Optional
import os
import math


@dataclass
class LSConfig:

    # ── Program identity ───────────────────────
    prog_name: str          = "WAAM_PROG"
    comment: str            = "Auto-generated by WAAM Slicer"

    # ── Tool / frame ───────────────────────────
    uframe: int             = 0
    utool: int              = 6

    # ── Weld schedules ─────────────────────────
    weld_start_s1: int      = 1
    weld_start_s2: int      = 3
    weld_end_s1: int        = 1
    weld_end_s2: int        = 3

    # ── Speed registers ────────────────────────
    travel_speed_reg: int   = 1
    weld_speed_reg: int     = 2
    dwell_reg: int          = 3

    travel_speed_val: float = 50.0    # mm/sec
    weld_speed_val: float   = 4.0     # mm/sec
    dwell_val: float        = 10.0    # sec

    # ── Inter-layer clearance ──────────────────
    # Set to 0 to disable lift — torch moves directly to next layer
    # start at travel speed. Only safe if wire retract is reliable.
    lift_clearance_mm: float = 0

    # ── Point reduction mode ──────────────────
    # "full"    : no reduction — all Shapely vertices kept.
    #             Guarantees geometrically exact paths. Large file.
    # "reduced" : Douglas-Peucker simplification at curve_tolerance_mm.
    #             Removes redundant curve points. Smaller file.
    # "custom"  : user sets curve_tolerance_mm explicitly.
    reduction_mode: str = "reduced"

    # ── Curve simplification ───────────────────
    # Maximum chord deviation for Douglas-Peucker (mm).
    # Only used when reduction_mode = "reduced" or "custom".
    # 0.5 mm is imperceptible at WAAM scale (5-8mm bead width).
    # Increase toward 2.0 for smaller files; decrease toward 0.1 for accuracy.
    curve_tolerance_mm: float = 0.5

    # Max distance between weld points — densification (0 = off).
    # Only needed for curved paths that the controller must interpolate.
    # Leave at 0 unless your controller cannot handle large point spacing.
    max_point_spacing_mm: float = 0.0

    # ── Lift clearance ─────────────────────────
    # Already in lift_clearance_mm above. Set to 0 to disable lift entirely.
    # When 0: direct single move from layer end to next layer start.
    # Saves 2 travel points per layer transition (significant for many layers).


class LSGenerator:

    def __init__(self, config: LSConfig = None):
        self.cfg        = config or LSConfig()
        self.lines      = []
        self.points     = []
        self._line_num  = 1
        self._pt_num    = 1
        self._stats     = {}   # populated by generate()

    def generate(self, layers) -> str:
        self.lines     = []
        self.points    = []
        self._line_num = 1
        self._pt_num   = 1

        self._write_header()
        self._write_registers()

        for layer_idx, layer in enumerate(layers):
            self._write_layer(layer, layer_idx, layers)

        self._write_footer()
        self._write_positions()

        content = "\n".join(self.lines)
        self._stats = {
            "total_points":  len(self.points),
            "program_lines": self._line_num - 1,
            "size_bytes":    len(content.encode("utf-8")),
        }
        return content

    def save(self, path: str, layers):
        content = self.generate(layers)
        os.makedirs(os.path.dirname(os.path.abspath(path)),
                    exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        sz_kb = self._stats["size_bytes"] / 1024
        print(f"  LS file saved  : {path}")
        print(f"  Layers         : {len(layers)}")
        print(f"  Total points   : {self._stats['total_points']}")
        print(f"  Program lines  : {self._stats['program_lines']}")
        print(f"  File size      : {sz_kb:.1f} KB")
        if sz_kb > 1500:
            print(f"  WARNING: File may exceed controller memory. "
                  f"Increase curve_tolerance_mm to reduce point count.")

    # ── Header / footer ───────────────────────

    def _write_header(self):
        cfg = self.cfg
        self.lines += [
            f"/PROG  {cfg.prog_name}",
            "/ATTR",
            "OWNER\t\t= MNEDITOR;",
            f'COMMENT\t\t= "{cfg.comment}";',
            "PROG_SIZE\t= 0;",
            "LINE_COUNT\t= 0;",
            "MEMORY_SIZE\t= 0;",
            "PROTECT\t\t= READ_WRITE;",
            "DEFAULT_GROUP\t= 1,*,*,*,*;",
            "/MN",
        ]

    def _write_registers(self):
        cfg = self.cfg
        self._mn(f"UFRAME_NUM={cfg.uframe}")
        self._mn(f"UTOOL_NUM={cfg.utool}")
        self._comment("Register definitions")
        self._mn(f"R[{cfg.travel_speed_reg}]={cfg.travel_speed_val:.0f}")
        self._comment("Travel speed mm/sec")
        self._mn(f"R[{cfg.weld_speed_reg}]={cfg.weld_speed_val:.0f}")
        self._comment("Weld speed mm/sec")
        self._mn(f"R[{cfg.dwell_reg}]={cfg.dwell_val:.0f}")
        self._comment("Interlayer dwell sec")

    def _write_footer(self):
        self.lines.append("/POS")

    def _write_positions(self):
        cfg = self.cfg
        for i, point in enumerate(self.points, start=1):
            x, y, z, w, p, r = point
            self.lines += [
                f"P[{i}]{{",
                "   GP1:",
                f"\tUF : {cfg.uframe}, UT : {cfg.utool},"
                f"\t\tCONFIG : 'N U T, 0, 0, 0',",
                f"\tX = {x:>10.3f}  mm,\tY = {y:>10.3f}  mm,"
                f"\tZ = {z:>10.3f}  mm,",
                f"\tW = {w:>7.3f} deg,\tP = {p:>7.3f} deg,"
                f"\tR = {r:>7.3f} deg",
                "};",
            ]
        self.lines.append("/END")
        self.lines.append("")   # trailing newline required by controller

    # ── Layer writer ──────────────────────────

    def _write_layer(self, layer, layer_idx: int,
                     all_layers: list):
        cfg      = self.cfg
        segments = self._collect_segments(layer)
        if not segments:
            return

        self._blank()

        # Extract WPR for this layer
        # getattr gracefully handles layers without wpr (e.g. from
        # older code or non-tilt runs where the field may not exist)
        wpr = getattr(layer, 'wpr', (0.0, 0.0, -70.0))

        # ── Per-layer weld speed (adaptive bead model) ────────────
        layer_weld_speed = getattr(layer, 'weld_speed_mms', None)
        spd_note = (f"  spd={layer_weld_speed:.1f}mm/s"
                    if layer_weld_speed is not None else "")

        self._comment(f"----- LAYER {layer_idx + 1} "
                      f"(z={layer.z:.2f}mm){spd_note}  "
                      f"W={wpr[0]:.1f} P={wpr[1]:.1f} R={wpr[2]:.1f} -----")

        # Write per-layer speed BEFORE the dwell — controller must have
        # the correct R[2] value when the arc starts after the wait.
        if layer_weld_speed is not None:
            spd_int = max(1, round(layer_weld_speed))
            self._mn(f"R[{cfg.weld_speed_reg}]={spd_int}")
            self._comment(f"Adaptive weld speed layer {layer_idx + 1} "
                          f"(model: {layer_weld_speed:.2f} mm/sec)")

        self._mn(f"WAIT R[{cfg.dwell_reg}]")
        self._blank()

        z = layer.z

        last_weld_pt = None  # track last deposited XY position

        for seg_idx, seg in enumerate(segments):
            pts            = seg["pts"]
            speed_override = seg["speed"]

            if not pts:
                continue

            # ── Reduce points first so we know the true start ─────
            reduced = self._reduce_points(pts)
            if not reduced:
                continue

            # ── Approach segment start ────────────────────────────
            sx, sy = reduced[0]

            if layer_idx == 0 and seg_idx == 0:
                # First ever move: optional lift approach
                if cfg.lift_clearance_mm > 0:
                    p_above = self._add_point(sx, sy,
                                              z + cfg.lift_clearance_mm,
                                              wpr)
                    self._move_travel(p_above)
                p_start = self._add_point(sx, sy, z, wpr)
                self._move_travel(p_start)
            else:
                # Skip air move if we are already at the start point
                if last_weld_pt is not None:
                    lx, ly = last_weld_pt
                    if math.hypot(sx - lx, sy - ly) > 0.1:
                        p_start = self._add_point(sx, sy, z, wpr)
                        self._move_travel(p_start)
                else:
                    p_start = self._add_point(sx, sy, z, wpr)
                    self._move_travel(p_start)

            # ── Weld Start ────────────────────────────────────────
            self._mn(f"Weld Start[{cfg.weld_start_s1},"
                     f"{cfg.weld_start_s2}]")

            # ── Weld points ───────────────────────────────────────
            for pt in reduced:
                p = self._add_point(*pt, z, wpr)
                if speed_override is not None:
                    # Fanuc R-30iB requires integer mm/sec in move
                    # statements — decimal values cause syntax errors.
                    spd_int = max(1, round(speed_override))
                    self._mn(f"L P[{p}] "
                             f"{spd_int}mm/sec CNT100")
                else:
                    self._mn(f"L P[{p}] "
                             f"R[{cfg.weld_speed_reg}]mm/sec CNT100")

            last_weld_pt = reduced[-1]

            # ── Weld End ──────────────────────────────────────────
            self._mn(f"Weld End[{cfg.weld_end_s1},"
                     f"{cfg.weld_end_s2}]")

        # ── Inter-layer travel ────────────────────────────────────
        is_last = (layer_idx == len(all_layers) - 1)
        if not is_last:
            next_layer = all_layers[layer_idx + 1]
            next_segs  = self._collect_segments(next_layer)
            if next_segs and next_segs[0]["pts"]:
                nx, ny    = next_segs[0]["pts"][0]
                nz        = next_layer.z
                lx, ly    = segments[-1]["pts"][-1]
                next_wpr  = getattr(next_layer, 'wpr', (0.0, 0.0, -70.0))

                if cfg.lift_clearance_mm > 0:
                    # Three-move inter-layer: lift → travel → descend
                    # Lift retains current layer WPR (torch held in position).
                    # Travel point transitions to next layer WPR so the torch
                    # is already oriented when it descends to deposit.
                    p_lift    = self._add_point(
                        lx, ly, z + cfg.lift_clearance_mm, wpr)
                    p_travel  = self._add_point(
                        nx, ny, z + cfg.lift_clearance_mm, next_wpr)
                    p_descend = self._add_point(nx, ny, nz, next_wpr)
                    self._move_travel(p_lift)
                    self._move_travel(p_travel)
                    self._move_travel(p_descend)
                else:
                    # No lift — single direct move, transition WPR at once
                    p_next = self._add_point(nx, ny, nz, next_wpr)
                    self._move_travel(p_next)

    # ── Segment collection ────────────────────

    def _collect_segments(self, layer) -> List[dict]:
        """
        Collect all deposition segments from a layer.

        Wall ring polygons are difference polygons (outer - inner) and
        may produce MultiPolygon results containing sliver geoms —
        thin connector pieces whose exterior.coords cross the interior
        hole, producing a long "travel" segment that ends up inside
        Weld Start. Filter these by checking geom area.

        Contour infill paths may have large "jump" gaps when a contour
        ring is split by the slicer — these appear as long straight
        segments inside a Weld Start block. Split any path at gaps
        larger than max_jump_mm to isolate them as separate segments
        with their own Weld Start/End brackets.
        """
        # Any segment in a path longer than this is considered a travel
        # move mistakenly included in a weld path — split there.
        # Default: 3× bead width. Adjust if needed.
        max_jump_mm = 30.0

        segments = []

        for wall in layer.walls:
            # ── Thin-wall centreline path (LineString) ─────────────
            # _compute_walls returns a LineString for thin solid polygons.
            # Deposit it as a single open weld pass — no exterior required.
            from shapely.geometry import LineString as _LS
            if isinstance(wall, _LS):
                pts = list(wall.coords)
                if len(pts) >= 2:
                    segments.append({"pts": pts, "speed": None})
                continue

            # ── Normal ring polygon wall ────────────────────────────
            geoms = wall.geoms if hasattr(wall, "geoms") else [wall]
            for g in geoms:
                if not hasattr(g, "exterior"):
                    continue
                try:
                    if g.area < 1.0:
                        continue
                except Exception:
                    pass
                pts = list(g.exterior.coords)
                if len(pts) >= 2:
                    for sub in self._split_at_jumps(pts, max_jump_mm):
                        segments.append({"pts": sub, "speed": None})

        for path in layer.infill_paths:
            pts = list(path.coords)
            if len(pts) >= 2:
                for sub in self._split_at_jumps(pts, max_jump_mm):
                    segments.append({"pts": sub, "speed": None})

        for ep, ep_speed in layer.edge_passes:
            pts = list(ep.coords)
            if len(pts) >= 2:
                segments.append({"pts": pts, "speed": ep_speed})

        return segments

    def _split_at_jumps(self, pts: List[Tuple],
                         max_gap_mm: float) -> List[List[Tuple]]:
        """
        Split a path at any segment longer than max_gap_mm.

        When a contour ring or wall exterior contains a long straight
        segment crossing the interior (a "jump"), splitting there
        ensures each sub-path is deposited as a separate weld pass
        with correct Weld Start/End brackets. The jump itself becomes
        an air travel move rather than a weld move.

        Returns a list of sub-paths (each is a list of (x,y) tuples).
        If no jumps found, returns [pts].
        """
        if len(pts) < 2 or max_gap_mm <= 0:
            return [pts]

        sub_paths = []
        current   = [pts[0]]

        for i in range(1, len(pts)):
            gap = math.hypot(pts[i][0] - pts[i-1][0],
                             pts[i][1] - pts[i-1][1])
            if gap > max_gap_mm:
                # Cut here — end current sub-path, start new one
                if len(current) >= 2:
                    sub_paths.append(current)
                current = [pts[i]]
            else:
                current.append(pts[i])

        if len(current) >= 2:
            sub_paths.append(current)

        return sub_paths if sub_paths else [pts]

    # ── Point reduction pipeline ──────────────
    # Applied to every segment before writing to LS.
    # Pipeline: Douglas-Peucker → collinear removal → dedup

    def _is_closed_ring(self, pts: List[Tuple]) -> bool:
        """True if first and last point are the same (closed ring)."""
        if len(pts) < 3:
            return False
        return math.hypot(pts[0][0] - pts[-1][0],
                          pts[0][1] - pts[-1][1]) < 0.01

    def _reduce_points(self, pts: List[Tuple]) -> List[Tuple]:
        """
        Full point reduction pipeline.

        Handles two path types:
          Open path (raster line): run DP directly.
          Closed ring (wall/contour): split at diametrically opposite point,
            run DP on each half, rejoin. The closing point is preserved
            through dedup — it is intentional, not a duplicate.

        Pipeline: DP → collinear removal → optional densify → dedup
        """
        if len(pts) <= 2:
            return list(pts)

        # Record closure BEFORE any processing — used to restore after dedup
        is_closed = self._is_closed_ring(pts)

        mode = self.cfg.reduction_mode
        tol  = self.cfg.curve_tolerance_mm

        if mode == "full":
            # Full mode: keep all original points, skip DP
            pass
        else:
            if tol <= 0:
                tol = 0.5
            if is_closed:
                pts = self._douglas_peucker_closed(pts, tol)
            else:
                pts = self._douglas_peucker(pts, tol)

        # Remember whether this was a closed ring BEFORE any processing
        # so we can restore the closing point after dedup.
        # The closing point is intentional (torch returns to seam) —
        # dedup must not remove it.
        was_closed = is_closed

        pts = self._remove_collinear(pts)

        if self.cfg.max_point_spacing_mm > 0:
            pts = self._densify(pts, self.cfg.max_point_spacing_mm)

        pts = self._dedup(pts)

        # Restore closing point for rings — dedup may have removed it
        # because pts[-1] == pts[0] after DP. Without it, the torch
        # stops at the last intermediate point and leaves a gap at the seam.
        if was_closed and len(pts) >= 2:
            if math.hypot(pts[-1][0] - pts[0][0],
                          pts[-1][1] - pts[0][1]) > 0.01:
                pts.append(pts[0])

        return pts

    def _douglas_peucker(self, pts: List[Tuple],
                          tolerance: float) -> List[Tuple]:
        """
        Douglas-Peucker simplification for OPEN polylines.

        Removes intermediate points whose perpendicular distance from
        the chord between their neighbours is below tolerance.
        For WAAM at 5-8mm bead width, 0.5mm tolerance is imperceptible.

        DO NOT pass closed rings (pts[0] == pts[-1]) — use
        _douglas_peucker_closed() instead. Closed rings have a
        zero-length baseline, causing this function to return only
        2 identical points (then dedup leaves 1 — the original bug).
        """
        if len(pts) <= 2:
            return list(pts)

        x1, y1 = pts[0][0], pts[0][1]
        x2, y2 = pts[-1][0], pts[-1][1]
        dx, dy  = x2 - x1, y2 - y1
        length  = math.hypot(dx, dy)

        if length < 1e-10:
            return [pts[0], pts[-1]]

        max_dist  = 0.0
        max_index = 0
        for i in range(1, len(pts) - 1):
            px, py = pts[i][0], pts[i][1]
            dist   = abs(dy * px - dx * py + x2 * y1 - y2 * x1) / length
            if dist > max_dist:
                max_dist  = dist
                max_index = i

        if max_dist > tolerance:
            left  = self._douglas_peucker(pts[:max_index + 1], tolerance)
            right = self._douglas_peucker(pts[max_index:], tolerance)
            return left[:-1] + right
        else:
            return [pts[0], pts[-1]]

    def _douglas_peucker_closed(self, pts: List[Tuple],
                                 tolerance: float) -> List[Tuple]:
        """
        Douglas-Peucker simplification for CLOSED rings.

        Standard DP fails on closed rings because the baseline
        (first → last point) has zero length, so ALL intermediate
        points appear to have zero perpendicular distance — the
        function immediately collapses the ring to 1 point.

        Fix: find the point FURTHEST from the first point (the
        diametrically opposite point on the ring), split the ring
        there into two open halves, run standard DP on each half,
        then rejoin. This gives a correct simplification.

        Example: 200-point ellipse at 0.5mm tolerance → ~24 points.
        """
        # Strip duplicate closing point if present
        work = pts[:-1] if self._is_closed_ring(pts) else list(pts)
        n    = len(work)

        if n <= 3:
            return list(pts)

        # Find the point furthest from work[0] — the "opposite" end
        x0, y0 = work[0]
        dists   = [math.hypot(work[i][0]-x0, work[i][1]-y0)
                   for i in range(n)]
        split_i = dists.index(max(dists))

        # Two open halves: 0..split_i and split_i..n-1..0
        half1 = work[:split_i + 1]                    # pts[0] → split
        half2 = work[split_i:] + [work[0]]            # split → pts[0]

        s1 = self._douglas_peucker(half1, tolerance)
        s2 = self._douglas_peucker(half2, tolerance)

        # Rejoin: s1 ends at split, s2 starts at split — remove duplicate
        combined = s1[:-1] + s2
        # Close the ring by appending first point
        if math.hypot(combined[-1][0]-combined[0][0],
                      combined[-1][1]-combined[0][1]) > 0.01:
            combined.append(combined[0])
        return combined

    def _remove_collinear(self, pts: List[Tuple],
                           tol: float = 0.01) -> List[Tuple]:
        if len(pts) <= 2:
            return pts

        def cross(o, a, b):
            return ((a[0]-o[0])*(b[1]-o[1])
                    - (a[1]-o[1])*(b[0]-o[0]))

        result = [pts[0]]
        for i in range(1, len(pts) - 1):
            if abs(cross(pts[i-1], pts[i], pts[i+1])) > tol:
                result.append(pts[i])
        result.append(pts[-1])
        return result

    def _densify(self, pts: List[Tuple],
                 max_spacing: float) -> List[Tuple]:
        if max_spacing <= 0 or len(pts) < 2:
            return pts
        result = [pts[0]]
        for i in range(1, len(pts)):
            x0, y0 = result[-1]
            x1, y1 = pts[i]
            dist   = math.hypot(x1-x0, y1-y0)
            if dist > max_spacing:
                n = int(dist / max_spacing)
                for k in range(1, n + 1):
                    t = k / (n + 1)
                    result.append((x0 + t*(x1-x0),
                                   y0 + t*(y1-y0)))
            result.append((x1, y1))
        return result

    def _dedup(self, pts: List[Tuple],
               tol: float = 0.001) -> List[Tuple]:
        if not pts:
            return pts
        result = [pts[0]]
        for pt in pts[1:]:
            if math.hypot(pt[0]-result[-1][0],
                          pt[1]-result[-1][1]) > tol:
                result.append(pt)
        return result

    # ── Low-level writers ─────────────────────

    def _mn(self, instruction: str):
        self.lines.append(f"{self._line_num}:{instruction} ;")
        self._line_num += 1

    def _comment(self, text: str):
        self.lines.append(f"{self._line_num}:! {text} ;")
        self._line_num += 1

    def _blank(self):
        self.lines.append(f"{self._line_num}: ;")
        self._line_num += 1

    def _move_travel(self, p_idx: int):
        cfg = self.cfg
        self._mn(f"L P[{p_idx}] "
                 f"R[{cfg.travel_speed_reg}]mm/sec CNT100")

    def _add_point(self, x: float, y: float, z: float,
                   wpr: tuple = None) -> int:
        """
        Store a position. wpr = (W, P, R) in degrees.
        If None, uses (0.0, 0.0, 0.0) — overridden by layer WPR
        in _write_layer calls.
        """
        w, p, r = wpr if wpr is not None else (0.0, 0.0, 0.0)
        self.points.append((x, y, z, w, p, r))
        idx = self._pt_num
        self._pt_num += 1
        return idx
